import { colours } from "./colours";

export const themes = {
  light: {
    background: colours.cultured,
    foreground: colours.white,
    text: colours.indigo,
    subtitle: colours.silver,
    primary: colours.aqua,
    icon: colours.electricBlue,
    danger: colours.red,
    error: colours.orange,
    emphasis: colours.black,
    indicator: colours.gray,
    selectedText: colours.white,
    separator: colours.indigo,
    tab: colours.gray,
    selectedTab: colours.aqua,
    handleIndicator: colours.lightGray,
    thumb: colours.lightGray,
  },
  dark: {
    background: colours.darkBlack,
    foreground: colours.gunmetal,
    text: colours.yonder,
    subtitle: colours.silver,
    primary: colours.blueGreen,
    icon: colours.electricBlue,
    danger: colours.red,
    error: colours.orange,
    emphasis: colours.white,
    indicator: colours.darkGunmetal,
    selectedText: colours.gunmetal,
    separator: colours.electricBlue,
    tab: colours.darkGunmetal,
    selectedTab: colours.blueGreen,
    handleIndicator: colours.electricBlue,
    thumb: colours.gunmetal,
  },
};
